### ISSUE TITLE
Can you please upload a read me file for how to use it?

### ISSUE THREAD

**Issue by arsalan993** [harshitbansal1602/Text-Recognition-in-scene-images#1]
Also which one is the weight file and what is the overall accuracy and precision?

**Comment by harshitbansal1602** [comment]
Hey, @arsalan993 
I have uploaded the readme; I will soon do tests on some popular datasets and attach results too in it. For now, I am closing the issue if you still need any further assistance with the working or usage, feel free to re-open the issue.
